# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdI4sVar5jT2GsKnb7yRW__Vmjnvrs8B
"""

import streamlit as st
import numpy as np
import joblib
from tensorflow.keras.models import load_model

# Load model and scaler
model = load_model("../models/lstm_model.h5")
scaler = joblib.load("../models/scaler.gz")

# Streamlit App
st.title("📈 DemandPulse: Sales Forecasting")

st.write("Input the last 10 days of sales to forecast the next day.")

# User input
sales_input = []
for i in range(10):
    sales = st.number_input(f"Day {i+1} Sales", min_value=0.0, step=1.0)
    sales_input.append(sales)

# Predict
if st.button("Forecast Next Day Sales"):
    scaled = scaler.transform(np.array(sales_input).reshape(-1, 1))
    X = np.array(scaled).reshape((1, 10, 1))
    pred_scaled = model.predict(X)
    prediction = scaler.inverse_transform(pred_scaled)

    st.success(f"📊 Predicted Sales: **{prediction[0][0]:.2f} units**")