# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjFTnanhqrVybNcfBaK_5uRzzCjuYtbK
"""

from fastapi import FastAPI
import numpy as np
from tensorflow.keras.models import load_model
import joblib

app = FastAPI()
model = load_model("models/lstm_model.h5")
scaler = joblib.load("models/scaler.gz")

@app.get("/")
def root():
    return {"message": "DemandPulse is live"}

@app.post("/predict")
def predict(sales: list[float]):
    scaled = scaler.transform(np.array(sales).reshape(-1, 1))
    X = np.array(scaled[-10:]).reshape((1, 10, 1))
    pred_scaled = model.predict(X)
    prediction = scaler.inverse_transform(pred_scaled)
    return {"predicted_sales": float(prediction[0][0])}