# -*- coding: utf-8 -*-
"""forecast

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWIfvtuZwWbivnhGmvuScacBORj-BeZY
"""

from src.preprocessing import load_and_preprocess_data
from src.model import create_lstm_model, prepare_sequences
from sklearn.model_selection import train_test_split
import joblib
import numpy as np

# Load and preprocess
df, scaler = load_and_preprocess_data('data/sales.csv')
X, y = prepare_sequences(df['sales_scaled'].values)

# Split and reshape
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))

# Train model
model = create_lstm_model((X_train.shape[1], 1))
model.fit(X_train, y_train, epochs=20)

# Save model
model.save('models/lstm_model.h5')
joblib.dump(scaler, 'models/scaler.gz')