# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mD67322q0u_eCW_uB_Zsms3LoDFVuWU5
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def load_and_preprocess_data(path):
    df = pd.read_csv(path, parse_dates=['date'])
    df.sort_values(by='date', inplace=True)
    scaler = MinMaxScaler()
    df['sales_scaled'] = scaler.fit_transform(df[['sales']])
    return df, scaler